version: '3.8'

x-trino-common: &trino-common
  image: localhost:5000/virtru/tdf-trino:0.6.0
  platform: linux/amd64
  restart: always
  healthcheck:
    test: ["CMD", "/usr/lib/trino/bin/health-check"]
    interval: 15s
    timeout: 10s
    retries: 5
    start_period: 120s
  depends_on:
    dsp:
      condition: service_healthy
      restart: true
  extra_hosts:
    local-dsp.virtru.com: "host-gateway"
  volumes:
    - ./trino-config/catalog:/etc/trino/catalog
    - ./trino-config/certs:/etc/trino/certs
    - ./trino-config/header-authenticator.properties:/etc/trino/header-authenticator.properties

services:
  tdf-trino-coordinator:
    <<: *trino-common
    container_name: tdf-trino-coordinator
    ports:
      - "28080:8080"
      - "28443:8443"
    volumes:
      - ./trino-config/catalog:/etc/trino/catalog
      - ./trino-config/certs:/etc/trino/certs
      - ./trino-config/coordinator/config.properties:/etc/trino/config.properties
      - ./trino-config/coordinator/jvm.config:/etc/trino/jvm.config
      - ./trino-config/header-authenticator.properties:/etc/trino/header-authenticator.properties

  # tdf-trino-worker-1:
  #   <<: *trino-common
  #   container_name: tdf-trino-worker-1
  #   volumes:
  #     - ./trino-config/catalog:/etc/trino/catalog
  #     - ./trino-config/certs:/etc/trino/certs
  #     - ./trino-config/worker/config.properties:/etc/trino/config.properties
  #     - ./trino-config/header-authenticator.properties:/etc/trino/header-authenticator.properties

  # tdf-trino-worker-2:
  #   <<: *trino-common
  #   container_name: tdf-trino-worker-2
  #   volumes:
  #     - ./trino-config/catalog:/etc/trino/catalog
  #     - ./trino-config/certs:/etc/trino/certs
  #     - ./trino-config/worker/config.properties:/etc/trino/config.properties
  #     - ./trino-config/header-authenticator.properties:/etc/trino/header-authenticator.properties
