coordinator=false
task.concurrency=4
task.max-worker-threads=4
query.max-memory=4GB
query.max-memory-per-node=2GB
http-server.http.port=8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/trino/certs/server.p12
http-server.https.keystore.key=changeit
internal-communication.shared-secret=trino-cop-shared-secret
discovery.uri=http://tdf-trino-coordinator:8080
